allowBuilds:
  '@firebase/util': set this to true or false
  '@fortawesome/fontawesome-free': set this to true or false
  core-js: set this to true or false
  core-js-pure: set this to true or false
  es5-ext: set this to true or false
  fsevents: set this to true or false
  protobufjs: set this to true or false
