import robotFallbackUrl from "../assets/doodles/robot-fallback.svg";
import leoModelUrl from "../assets/doodles/leo.glb";
import lunaModelUrl from "../assets/doodles/luna.glb";
import miraModelUrl from "../assets/doodles/mira.glb";
import robotModelUrl from "../assets/doodles/robot.glb";

export const doodleCatalog = [
  {
    id: "nova",
    name: "Nova",
    role: "Logical pronunciation helper",
    description: "Patient, precise, and great at breaking long words into clear sound steps.",
    color: "#0f766e",
    modelPath: robotModelUrl,
    fallbackImagePath: robotFallbackUrl,
    scale: 0.42,
    position: [0, -1.2, 0],
    camera: { position: [0, 1.25, 5], fov: 35 },
    shadowPosition: [0, -1.24, 0],
    sourceName: "Existing project robot",
    modelStatus: "ready",
    voice: {
      gender: "neutral",
      rate: 0.86,
      pitch: 1.05,
      ttsVoice: "en_US-lessac-medium.onnx",
      preferredNames: ["Samantha", "Google US English", "Alex"],
      preview: "Hi, I am Nova. I can help you say tricky words one sound at a time.",
    },
  },
  {
    id: "luna",
    name: "Luna",
    role: "Calm reading guide",
    description: "A soft, encouraging companion for slow reading, confidence, and emotional support.",
    color: "#7c3aed",
    modelPath: lunaModelUrl,
    fallbackImagePath: robotFallbackUrl,
    scale: 1.35,
    position: [0, -1.18, 0],
    camera: { position: [0, 1.25, 5.8], fov: 36 },
    shadowPosition: [0, -1.18, 0],
    sourceName: "Animated Woman 3D Model",
    modelStatus: "ready",
    voice: {
      gender: "female",
      rate: 0.82,
      pitch: 1.14,
      ttsVoice: "en_US-amy-medium.onnx",
      preferredNames: ["Samantha", "Google UK English Female", "Victoria"],
      preview: "Hi, I am Luna. I will read slowly with you and make every word feel smaller.",
    },
  },
  {
    id: "bob",
    name: "Bob",
    role: "Playful quiz coach",
    description: "Bright, curious, and ready to turn practice into quick voice quizzes.",
    color: "#c2410c",
    modelPath: miraModelUrl,
    fallbackImagePath: robotFallbackUrl,
    scale: 0.82,
    position: [0, -1.18, 0],
    camera: { position: [0, 1.25, 5.4], fov: 36 },
    shadowPosition: [0, -1.18, 0],
    sourceName: "Cube Guy Character by Quaternius",
    modelStatus: "ready",
    voice: {
      gender: "male",
      rate: 0.9,
      pitch: 0.96,
      ttsVoice: "en_US-ryan-medium.onnx",
      preferredNames: ["Alex", "Daniel", "Google US English"],
      preview: "Hi, I am Bob. I will quiz you with tiny questions and celebrate your answers.",
    },
  },
  {
    id: "leo",
    name: "Leo",
    role: "Friendly practice buddy",
    description: "Steady, warm, and focused on helping learners try again without pressure.",
    color: "#2563eb",
    modelPath: leoModelUrl,
    fallbackImagePath: robotFallbackUrl,
    scale: 1.45,
    position: [0, -1.18, 0],
    camera: { position: [0, 1.2, 5.6], fov: 36 },
    shadowPosition: [0, -1.2, 0],
    sourceName: "Shaun 3D Model by Quaternius",
    modelStatus: "ready",
    voice: {
      gender: "male",
      rate: 0.86,
      pitch: 0.92,
      ttsVoice: "en_GB-alan-medium.onnx",
      preferredNames: ["Alex", "Daniel", "Google UK English Male"],
      preview: "Hi, I am Leo. I will practice with you until the word feels easy.",
    },
  },
];
